version: '2'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: gunny_php
        build: .docker/php
        environment:
            - TZ=Asia/Seoul
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: gunny_nginx
        build: .docker/nginx
        environment:
            - TZ=Asia/Seoul
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .docker/nginx/logs:/var/log/nginx
        depends_on:
            - php


